### ISSUE TITLE
question: upgrading 0.6.5 deb -> 0.7.7 pkg 

### ISSUE THREAD

**Issue by maximlomans** [SBuild-org/sbuild#209]
would it be required to first uninstall the older version , would the latest version have any issues accessing chroots created by previous version ?
  i found nothing in docs about upgrading .

thanks

**Comment by lefou** [comment]
@marxenegls Looks like you hit the wrong project. Did you mean https://tracker.debian.org/pkg/sbuild ?

**Comment by maximlomans** [comment]
ooops, i guess i did
